server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

Spring:
  application:
    name: ead-authuser-service
  profiles:
    active: h2
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: Always
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course/'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost